import '../models/product.dart';

class ProductService {
  static final ProductService _instance = ProductService._internal();
  factory ProductService() => _instance;
  ProductService._internal();

  final Map<String, List<Product>> _products = {
    // Men's Products
    'men': [
      Product(
        id: 'men_1',
        name: 'Classic Dress Shirt',
        price: 49.99,
        imagePath: 'assets/images/products/men/men_1.jpg',
        category: 'men',
        description: 'Premium cotton dress shirt perfect for office wear.',
      ),
      Product(
        id: 'men_2',
        name: 'Casual Polo Shirt',
        price: 35.00,
        imagePath: 'assets/images/products/men/men_2.jpg',
        category: 'men',
        description: 'Comfortable polo shirt for everyday casual wear.',
      ),
      Product(
        id: 'men_3',
        name: 'Denim Jeans',
        price: 59.99,
        imagePath: 'assets/images/products/men/men_3.jpg',
        category: 'men',
        description: 'Durable and stylish denim jeans for men.',
      ),
      Product(
        id: 'men_4',
        name: 'Business Blazer',
        price: 120.00,
        imagePath: 'assets/images/products/men/men_4.jpg',
        category: 'men',
        description: 'Sharp blazer for business or formal occasions.',
      ),
      Product(
        id: 'men_5',
        name: 'Casual T-Shirt',
        price: 19.99,
        imagePath: 'assets/images/products/men/men_5.jpg',
        category: 'men',
        description: 'Soft cotton t-shirt for ultimate comfort.',
      ),
      Product(
        id: 'men_6',
        name: 'Chino Pants',
        price: 45.00,
        imagePath: 'assets/images/products/men/men_6.jpg',
        category: 'men',
        description: 'Versatile chino pants for smart casual looks.',
      ),
      Product(
        id: 'men_7',
        name: 'Leather Jacket',
        price: 180.00,
        imagePath: 'assets/images/products/men/men_7.jpg',
        category: 'men',
        description: 'Classic leather jacket for a rugged style.',
      ),
      Product(
        id: 'men_8',
        name: 'Hooded Sweatshirt',
        price: 40.00,
        imagePath: 'assets/images/products/men/men_8.jpg',
        category: 'men',
        description: 'Warm and cozy hooded sweatshirt for cooler days.',
      ),
      Product(
        id: 'men_9',
        name: 'Slim Fit Trousers',
        price: 65.00,
        imagePath: 'assets/images/products/men/men_9.jpg',
        category: 'men',
        description: 'Modern slim fit trousers for a tailored appearance.',
      ),
      Product(
        id: 'men_10',
        name: 'Sports Shorts',
        price: 25.00,
        imagePath: 'assets/images/products/men/men_10.jpg',
        category: 'men',
        description: 'Lightweight and breathable shorts for sports activities.',
      ),
    ],
    // Women's Products
    'women': [
      Product(
        id: 'women_1',
        name: 'Elegant Maxi Dress',
        price: 75.00,
        imagePath: 'assets/images/products/women/women_1.jpg',
        category: 'women',
        description: 'Flowy maxi dress perfect for summer evenings.',
      ),
      Product(
        id: 'women_2',
        name: 'High-Waisted Jeans',
        price: 60.00,
        imagePath: 'assets/images/products/women/women_2.jpg',
        category: 'women',
        description: 'Comfortable and flattering high-waisted denim jeans.',
      ),
      Product(
        id: 'women_3',
        name: 'Floral Blouse',
        price: 40.00,
        imagePath: 'assets/images/products/women/women_3.jpg',
        category: 'women',
        description: 'Light and airy blouse with a vibrant floral print.',
      ),
      Product(
        id: 'women_4',
        name: 'Pencil Skirt',
        price: 38.00,
        imagePath: 'assets/images/products/women/women_4.jpg',
        category: 'women',
        description: 'Classic pencil skirt for a sophisticated office look.',
      ),
      Product(
        id: 'women_5',
        name: 'Knitted Cardigan',
        price: 55.00,
        imagePath: 'assets/images/products/women/women_5.jpg',
        category: 'women',
        description: 'Soft knitted cardigan for layering and warmth.',
      ),
      Product(
        id: 'women_6',
        name: 'Casual Jumpsuit',
        price: 70.00,
        imagePath: 'assets/images/products/women/women_6.jpg',
        category: 'women',
        description: 'Stylish and comfortable jumpsuit for everyday wear.',
      ),
      Product(
        id: 'women_7',
        name: 'Denim Jacket',
        price: 65.00,
        imagePath: 'assets/images/products/women/women_7.jpg',
        category: 'women',
        description: 'Timeless denim jacket, a wardrobe essential.',
      ),
      Product(
        id: 'women_8',
        name: 'Striped T-Shirt',
        price: 22.00,
        imagePath: 'assets/images/products/women/women_8.jpg',
        category: 'women',
        description: 'Simple yet chic striped t-shirt for casual outfits.',
      ),
      Product(
        id: 'women_9',
        name: 'Wide Leg Trousers',
        price: 50.00,
        imagePath: 'assets/images/products/women/women_9.jpg',
        category: 'women',
        description: 'Fashionable wide leg trousers for a relaxed fit.',
      ),
      Product(
        id: 'women_10',
        name: 'Summer Shorts',
        price: 30.00,
        imagePath: 'assets/images/products/women/women_10.jpg',
        category: 'women',
        description: 'Lightweight shorts perfect for hot summer days.',
      ),
    ],
    // Kids' Products
    'kids': [
      Product(
        id: 'kids_1',
        name: 'Dinosaur T-Shirt',
        price: 15.99,
        imagePath: 'assets/images/products/kids/kids_1.jpg',
        category: 'kids',
        description: 'Fun and colorful t-shirt for kids with a dinosaur print.',
      ),
      Product(
        id: 'kids_2',
        name: 'Unicorn Dress',
        price: 25.99,
        imagePath: 'assets/images/products/kids/kids_2.jpg',
        category: 'kids',
        description: 'Sparkly unicorn dress for little princesses.',
      ),
      Product(
        id: 'kids_3',
        name: 'Kids Denim Overalls',
        price: 30.50,
        imagePath: 'assets/images/products/kids/kids_3.jpg',
        category: 'kids',
        description: 'Durable denim overalls for active kids.',
      ),
      Product(
        id: 'kids_4',
        name: 'Cartoon Print Hoodie',
        price: 22.00,
        imagePath: 'assets/images/products/kids/kids_4.jpg',
        category: 'kids',
        description: 'Cozy hoodie with a popular cartoon character print.',
      ),
      Product(
        id: 'kids_5',
        name: 'Striped Long Sleeve Top',
        price: 18.75,
        imagePath: 'assets/images/products/kids/kids_5.jpg',
        category: 'kids',
        description: 'Comfortable striped top for everyday wear.',
      ),
      Product(
        id: 'kids_6',
        name: 'Kids Jogger Pants',
        price: 19.99,
        imagePath: 'assets/images/products/kids/kids_6.jpg',
        category: 'kids',
        description: 'Soft and flexible jogger pants for play and comfort.',
      ),
      Product(
        id: 'kids_7',
        name: 'Animal Print Leggings',
        price: 14.50,
        imagePath: 'assets/images/products/kids/kids_7.jpg',
        category: 'kids',
        description: 'Stylish leggings with a fun animal print.',
      ),
      Product(
        id: 'kids_8',
        name: 'Kids Rain Jacket',
        price: 35.00,
        imagePath: 'assets/images/products/kids/kids_8.jpg',
        category: 'kids',
        description: 'Waterproof and colorful rain jacket for kids.',
      ),
      Product(
        id: 'kids_9',
        name: 'Graphic Tee',
        price: 12.00,
        imagePath: 'assets/images/products/kids/kids_9.jpg',
        category: 'kids',
        description: 'Cool graphic tee with a unique design.',
      ),
      Product(
        id: 'kids_10',
        name: 'Plaid Flannel Shirt',
        price: 20.00,
        imagePath: 'assets/images/products/kids/kids_10.jpg',
        category: 'kids',
        description: 'Classic plaid flannel shirt for a cozy look.',
      ),
    ],
    // Shoes Products
    'shoes': [
      Product(
        id: 'shoes_1',
        name: 'Running Sneakers',
        price: 89.99,
        imagePath: 'assets/images/products/shoes/shoes_1.jpg',
        category: 'shoes',
        description: 'Lightweight and comfortable sneakers for running.',
      ),
      Product(
        id: 'shoes_2',
        name: 'Casual Loafers',
        price: 70.00,
        imagePath: 'assets/images/products/shoes/shoes_2.jpg',
        category: 'shoes',
        description: 'Stylish and comfortable loafers for everyday wear.',
      ),
      Product(
        id: 'shoes_3',
        name: 'High Heels',
        price: 95.00,
        imagePath: 'assets/images/products/shoes/shoes_3.jpg',
        category: 'shoes',
        description: 'Elegant high heels for special occasions.',
      ),
      Product(
        id: 'shoes_4',
        name: 'Ankle Boots',
        price: 110.00,
        imagePath: 'assets/images/products/shoes/shoes_4.jpg',
        category: 'shoes',
        description: 'Fashionable ankle boots for a chic look.',
      ),
      Product(
        id: 'shoes_5',
        name: 'Sport Sandals',
        price: 45.00,
        imagePath: 'assets/images/products/shoes/shoes_5.jpg',
        category: 'shoes',
        description: 'Durable and comfortable sandals for outdoor activities.',
      ),
      Product(
        id: 'shoes_6',
        name: 'Formal Dress Shoes',
        price: 130.00,
        imagePath: 'assets/images/products/shoes/shoes_6.jpg',
        category: 'shoes',
        description: 'Classic dress shoes for formal events and business.',
      ),
      Product(
        id: 'shoes_7',
        name: 'Winter Boots',
        price: 150.00,
        imagePath: 'assets/images/products/shoes/shoes_7.jpg',
        category: 'shoes',
        description: 'Warm and waterproof boots for cold weather.',
      ),
      Product(
        id: 'shoes_8',
        name: 'Canvas Sneakers',
        price: 55.00,
        imagePath: 'assets/images/products/shoes/shoes_8.jpg',
        category: 'shoes',
        description: 'Versatile canvas sneakers for a casual style.',
      ),
      Product(
        id: 'shoes_9',
        name: 'Flip-Flops',
        price: 20.00,
        imagePath: 'assets/images/products/shoes/shoes_9.jpg',
        category: 'shoes',
        description: 'Simple and comfortable flip-flops for beach or home.',
      ),
      Product(
        id: 'shoes_10',
        name: 'Hiking Boots',
        price: 140.00,
        imagePath: 'assets/images/products/shoes/shoes_10.jpg',
        category: 'shoes',
        description: 'Sturdy hiking boots for challenging trails.',
      ),
    ],
    // Accessories Products
    'accessories': [
      Product(
        id: 'accessories_1',
        name: 'Leather Wallet',
        price: 30.00,
        imagePath: 'assets/images/products/accessories/accessories_1.jpg',
        category: 'accessories',
        description: 'Sleek leather wallet with multiple card slots.',
      ),
      Product(
        id: 'accessories_2',
        name: 'Fashion Sunglasses',
        price: 25.00,
        imagePath: 'assets/images/products/accessories/accessories_2.jpg',
        category: 'accessories',
        description: 'Trendy sunglasses for a stylish look.',
      ),
      Product(
        id: 'accessories_3',
        name: 'Wrist Watch',
        price: 80.00,
        imagePath: 'assets/images/products/accessories/accessories_3.jpg',
        category: 'accessories',
        description: 'Classic wrist watch with a minimalist design.',
      ),
      Product(
        id: 'accessories_4',
        name: 'Silk Scarf',
        price: 35.00,
        imagePath: 'assets/images/products/accessories/accessories_4.jpg',
        category: 'accessories',
        description: 'Luxurious silk scarf for added elegance.',
      ),
      Product(
        id: 'accessories_5',
        name: 'Baseball Cap',
        price: 18.00,
        imagePath: 'assets/images/products/accessories/accessories_5.jpg',
        category: 'accessories',
        description: 'Adjustable baseball cap for casual wear.',
      ),
      Product(
        id: 'accessories_6',
        name: 'Statement Necklace',
        price: 45.00,
        imagePath: 'assets/images/products/accessories/accessories_6.jpg',
        category: 'accessories',
        description: 'Bold necklace to complete any outfit.',
      ),
      Product(
        id: 'accessories_7',
        name: 'Leather Belt',
        price: 30.00,
        imagePath: 'assets/images/products/accessories/accessories_7.jpg',
        category: 'accessories',
        description: 'Durable leather belt with a classic buckle.',
      ),
      Product(
        id: 'accessories_8',
        name: 'Beanie Hat',
        price: 20.00,
        imagePath: 'assets/images/products/accessories/accessories_8.jpg',
        category: 'accessories',
        description: 'Warm beanie hat for cold weather.',
      ),
      Product(
        id: 'accessories_9',
        name: 'Crossbody Bag',
        price: 55.00,
        imagePath: 'assets/images/products/accessories/accessories_9.jpg',
        category: 'accessories',
        description: 'Compact crossbody bag for essentials.',
      ),
      Product(
        id: 'accessories_10',
        name: 'Gloves',
        price: 28.00,
        imagePath: 'assets/images/products/accessories/accessories_10.jpg',
        category: 'accessories',
        description: 'Soft and warm gloves for winter.',
      ),
    ],
    // Winter Collection Products
    'winter_collection': [
      Product(
        id: 'winter_1',
        name: 'Wool Coat',
        price: 180.00,
        imagePath: 'assets/images/products/winter_collection/winter_collection_1.jpg',
        category: 'winter_collection',
        description: 'Elegant wool coat for extreme cold.',
      ),
      Product(
        id: 'winter_2',
        name: 'Puffer Jacket',
        price: 150.00,
        imagePath: 'assets/images/products/winter_collection/winter_collection_2.jpg',
        category: 'winter_collection',
        description: 'Warm and lightweight puffer jacket.',
      ),
      Product(
        id: 'winter_3',
        name: 'Thermal Leggings',
        price: 30.00,
        imagePath: 'assets/images/products/winter_collection/winter_collection_3.jpg',
        category: 'winter_collection',
        description: 'Insulated leggings for extra warmth.',
      ),
      Product(
        id: 'winter_4',
        name: 'Fleece Hoodie',
        price: 50.00,
        imagePath: 'assets/images/products/winter_collection/winter_collection_4.jpg',
        category: 'winter_collection',
        description: 'Soft fleece hoodie for cozy comfort.',
      ),
      Product(
        id: 'winter_5',
        name: 'Knitted Sweater',
        price: 65.00,
        imagePath: 'assets/images/products/winter_collection/winter_collection_5.jpg',
        category: 'winter_collection',
        description: 'Classic knitted sweater for winter fashion.',
      ),
      Product(
        id: 'winter_6',
        name: 'Snow Pants',
        price: 90.00,
        imagePath: 'assets/images/products/winter_collection/winter_collection_6.jpg',
        category: 'winter_collection',
        description: 'Waterproof snow pants for winter sports.',
      ),
      Product(
        id: 'winter_7',
        name: 'Down Vest',
        price: 80.00,
        imagePath: 'assets/images/products/winter_collection/winter_collection_7.jpg',
        category: 'winter_collection',
        description: 'Lightweight down vest for core warmth.',
      ),
      Product(
        id: 'winter_8',
        name: 'Long Sleeve Thermal Top',
        price: 35.00,
        imagePath: 'assets/images/products/winter_collection/winter_collection_8.jpg',
        category: 'winter_collection',
        description: 'Base layer thermal top for cold weather activities.',
      ),
      Product(
        id: 'winter_9',
        name: 'Winter Scarf',
        price: 25.00,
        imagePath: 'assets/images/products/winter_collection/winter_collection_9.jpg',
        category: 'winter_collection',
        description: 'Thick and warm scarf for winter protection.',
      ),
      Product(
        id: 'winter_10',
        name: 'Insulated Gloves',
        price: 40.00,
        imagePath: 'assets/images/products/winter_collection/winter_collection_10.jpg',
        category: 'winter_collection',
        description: 'High-performance insulated gloves for extreme cold.',
      ),
    ],
    // Activewear Products
    'activewear': [
      Product(
        id: 'activewear_1',
        name: 'Gym Leggings',
        price: 45.00,
        imagePath: 'assets/images/products/activewear/activewear_1.jpg',
        category: 'activewear',
        description: 'High-waisted, breathable leggings for gym workouts.',
      ),
      Product(
        id: 'activewear_2',
        name: 'Sports Tee',
        price: 28.00,
        imagePath: 'assets/images/products/activewear/activewear_2.jpg',
        category: 'activewear',
        description: 'Moisture-wicking sports tee for intense training.',
      ),
      Product(
        id: 'activewear_3',
        name: 'Track Pants',
        price: 50.00,
        imagePath: 'assets/images/products/activewear/activewear_3.jpg',
        category: 'activewear',
        description: 'Comfortable track pants for running or casual wear.',
      ),
      Product(
        id: 'activewear_4',
        name: 'Yoga Bra',
        price: 35.00,
        imagePath: 'assets/images/products/activewear/activewear_4.jpg',
        category: 'activewear',
        description: 'Supportive and comfortable bra for yoga and low-impact activities.',
      ),
      Product(
        id: 'activewear_5',
        name: 'Running Jacket',
        price: 70.00,
        imagePath: 'assets/images/products/activewear/activewear_5.jpg',
        category: 'activewear',
        description: 'Lightweight running jacket with reflective details.',
      ),
      Product(
        id: 'activewear_6',
        name: 'Compression Shorts',
        price: 30.00,
        imagePath: 'assets/images/products/activewear/activewear_6.jpg',
        category: 'activewear',
        description: 'Tight-fit compression shorts for muscle support.',
      ),
      Product(
        id: 'activewear_7',
        name: 'Athletic Hoodie',
        price: 55.00,
        imagePath: 'assets/images/products/activewear/activewear_7.jpg',
        category: 'activewear',
        description: 'Warm athletic hoodie for pre and post-workout.',
      ),
      Product(
        id: 'activewear_8',
        name: 'Tank Top',
        price: 20.00,
        imagePath: 'assets/images/products/activewear/activewear_8.jpg',
        category: 'activewear',
        description: 'Breathable tank top for high-intensity workouts.',
      ),
      Product(
        id: 'activewear_9',
        name: 'Sports Socks',
        price: 15.00,
        imagePath: 'assets/images/products/activewear/activewear_9.jpg',
        category: 'activewear',
        description: 'Cushioned sports socks for enhanced comfort.',
      ),
      Product(
        id: 'activewear_10',
        name: 'Windbreaker Vest',
        price: 60.00,
        imagePath: 'assets/images/products/activewear/activewear_10.jpg',
        category: 'activewear',
        description: 'Lightweight windbreaker vest for outdoor training.',
      ),
    ],
  };

  List<Product> getProductsByCategory(String category) {
    return _products[category.toLowerCase()] ?? [];
  }

  List<Product> getAllProducts() {
    List<Product> allProducts = [];
    _products.values.forEach((products) {
      allProducts.addAll(products);
    });
    return allProducts;
  }

  List<Product> getFeaturedProducts() {
    List<Product> featured = [];
    _products.values.forEach((products) {
      if (products.isNotEmpty) {
        featured.add(products.first);
      }
    });
    return featured;
  }

  List<String> getCategories() {
    return ['Men', 'Women', 'Kids', 'Shoes', 'Accessories', 'Winter Collection', 'Activewear'];
  }
}

